services:
  server:
    build:
        context: .
        dockerfile: Dockerfile.server
    ports:
      - "1337:1337"
    volumes:
      - "./content:/app/content:ro"
    command: ["python", "server.py", "-d", "/app/content"]

  requester:
    build:
        context: .
        dockerfile: Dockerfile.requester
    volumes:
      - "./content/downloads:/app/content/downloads"
    command: ["tail", "-f", "/dev/null"]
    extra_hosts:
        - "host.docker.internal:host-gateway"